version: '3.1'

services:

 adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_PLUGINS: frames
      ADMINER_OTP_SECRET: ${ADMINER_OTP_SECRET}
    volumes:
      - ./plugins/login-otp.php:/var/www/html/plugins-enabled/login-otp.php:ro
    ports:
      - 80:8080

